[versions]
cdt="4.0.0" # chrome-developer-toolkit
commonmark = "0.18.0"
compose = "1.2.1"
freemarker = "2.3.31"
jreleaser = "1.3.1"
jsoup = "1.14.3"
kaml = "0.35.3"
kobweb-cli = "0.9.11-SNAPSHOT"
kobweb-libs = "0.10.7-SNAPSHOT"
kotter = "1.0.0"
kotlin = "1.7.20"
kotlinpoet = "1.10.2"
kotlinx-coroutines = "1.6.0"
kotlinx-cli = "0.3.2"
kotlinx-html = "0.7.3"
kotlinx-serialization-json = "1.4.1"
ksp = "1.5.30-1.0.0"
ktor = "1.6.4"
logback = "1.2.3"
truthish = "0.6.0"
shadow = "7.0.0"

[libraries]
cdt = { module = "com.github.kklisura.cdt:cdt-java-client", version.ref = "cdt" }
commonmark-core = { module = "org.commonmark:commonmark", version.ref = "commonmark" }
commonmark-autolink = { module = "org.commonmark:commonmark-ext-autolink", version.ref = "commonmark" }
commonmark-frontmatter = { module = "org.commonmark:commonmark-ext-yaml-front-matter", version.ref = "commonmark" }
commonmark-tables = { module = "org.commonmark:commonmark-ext-gfm-tables", version.ref = "commonmark" }
commonmark-tasklist = { module = "org.commonmark:commonmark-ext-task-list-items", version.ref = "commonmark" }
freemarker = { module = "org.freemarker:freemarker", version.ref = "freemarker"}
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
kotter = { module = "com.varabyte.kotter:kotter", version.ref = "kotter" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-cli = { module = "org.jetbrains.kotlinx:kotlinx-cli", version.ref = "kotlinx-cli" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html", version.ref = "kotlinx-html" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ktor-auth = { module = "io.ktor:ktor-auth", version.ref = "ktor"}
ktor-serialization = { module = "io.ktor:ktor-serialization", version.ref = "ktor"}
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-host-common = { module = "io.ktor:ktor-server-host-common", version.ref = "ktor"}
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor"}
ktor-server-tests = { module = "io.ktor:ktor-server-tests", version.ref = "ktor"}
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
truthish = { module = "com.varabyte.truthish:truthish", version.ref = "truthish" }

[bundles]
commonmark = ["commonmark-core", "commonmark-autolink", "commonmark-frontmatter","commonmark-tables","commonmark-tasklist"]
ktor = ["ktor-server-core", "ktor-serialization", "ktor-auth", "ktor-server-host-common", "ktor-server-netty", "logback"]

[plugins]
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
